<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Bella.Wms.Platform.Abstractions/Bella.Wms.Platform.Abstractions.csproj" />
    <ProjectReference Include="../Bella.Wms.Platform.Audit/Bella.Wms.Platform.Audit.csproj" />
    <ProjectReference Include="../Bella.Wms.Platform.Config/Bella.Wms.Platform.Config.csproj" />
    <ProjectReference Include="../Bella.Wms.Platform.Identity/Bella.Wms.Platform.Identity.csproj" />
    <ProjectReference Include="../../Modules/Bella.Wms.Integration.Partners/Application/Bella.Wms.Integration.Partners.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>
</Project>
